export const dynamic = "force-dynamic";

// app/api/deliberations/ensure/route.ts
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prismaclient";
import { getCurrentUserId } from "@/lib/serverutils";
import { emitBus } from "@/lib/server/bus";
import { jsonSafe } from "@/lib/bigintjson";
import { ensureBaselineLudicsDesigns } from "@/lib/ludics/ensureBaseline";
import { onDeliberationCreated } from "@/lib/triggers/knowledgeGraphTriggers";
import { TargetType } from "@prisma/client";
import { z } from "zod";

const Allowed = new Set([
  "article",
  "post",
  "room_thread",
  "library_stack",
  "site",
  "inbox_thread",
] as const);

const Body = z.object({
  hostType: z.string(),
  hostId: z.string(),
  // Optional human-chosen name for the new deliberation (Phase 4). When
  // omitted we fall back to the discussion topic as a flagged auto-title.
  title: z.string().max(200).nullable().optional(),
  anchor: z
    .object({
      targetType: z.string().optional(),
      targetId: z.string().nullable().optional(),
      selectorJson: z.any().optional(),
      title: z.string().nullable().optional(),
      snippet: z.string().nullable().optional(),
    })
    .optional(),
});

export async function POST(req: NextRequest) {
  const me = await getCurrentUserId();
  if (!me) return NextResponse.json({ error: "Unauthenticated" }, { status: 401 });

  const parsed = Body.safeParse(await req.json().catch(() => null));
  if (!parsed.success) return NextResponse.json({ error: "Bad body" }, { status: 400 });

  let { hostType, hostId, anchor } = parsed.data;

  // Phase 4: deterministic title prefill from the source discussion topic.
  let discussionTopic: string | null = null;

  // Map synthetic host type "discussion" → enum-backed "inbox_thread"
  if (hostType === "discussion") {
    const discussion = await prisma.discussion.findUnique({
      where: { id: hostId },
      select: { conversationId: true, title: true },
    });
    if (!discussion) {
      return NextResponse.json({ error: "Discussion not found" }, { status: 404 });
    }

    discussionTopic = discussion.title?.trim() || null;

    let convId = discussion.conversationId;
    if (!convId) {
      // Ensure a conversation exists for this discussion
      const conv = await prisma.$transaction(async (tx) => {
        const c = await tx.conversation.create({ data: {} });
        await tx.discussion.update({ where: { id: hostId }, data: { conversationId: c.id } });
        return c;
      });
      convId = conv.id;
    }

    hostType = "inbox_thread";
    hostId = String(convId);
  }

  if (!Allowed.has(hostType as any)) {
    return NextResponse.json({ error: `Invalid hostType '${hostType}'` }, { status: 400 });
  }

  let d = await prisma.deliberation.findFirst({
    where: { hostType: hostType as any, hostId },
    select: { id: true },
  });

  let created = false;
  if (!d) {
    // Phase 4 title precedence: explicit human title wins; otherwise prefill
    // from the discussion topic as a flagged auto-title (upgradeable later).
    const explicitTitle = parsed.data.title?.trim();
    const titleFields = explicitTitle
      ? { title: explicitTitle, titleAutoGenerated: false }
      : discussionTopic
        ? { title: discussionTopic, titleAutoGenerated: true }
        : {};

    d = await prisma.deliberation.create({
      data: { hostType: hostType as any, hostId, createdById: String(me), ...titleFields },
      select: { id: true },
    });
    created = true;
    emitBus("deliberations:created", { id: d.id, hostType, hostId, source: "ensure" });
    // Trigger knowledge graph update
    onDeliberationCreated(d.id).catch(console.error);
    // 👇 Ensure baseline Ludics designs exist so DeepDivePanel has something to render.

   try {
      const { proId, oppId } = await ensureBaselineLudicsDesigns({
        deliberationId: d.id,
        participantId: String(me),
        seedActs: true,
      });
      
    } catch (e) {
      console.warn("[ludics] baseline seed failed:", e);
    }
   }
  let anchorId: string | undefined;
  if (anchor) {
    const a = await prisma.deliberationAnchor.create({
      data: {
        deliberationId: d.id,
        targetType: anchor.targetType ?? "unknown",
        targetId: anchor.targetId ?? null,
        selectorJson: anchor.selectorJson ?? null,
        title: anchor.title ?? null,
        snippet: anchor.snippet ?? null,
        createdById: String(me),
      },
      select: { id: true },
    });
    anchorId = a.id;
  }

 return NextResponse.json(jsonSafe({ id: d.id, created, anchorId }));
}
