# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ranker.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ranker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cranker.proto\"7\n\x0bRankRequest\x12\x11\n\tviewer_id\x18\x01 \x01(\t\x12\x15\n\rcandidate_ids\x18\x02 \x03(\t\"\"\n\x0cRankResponse\x12\x12\n\nranked_ids\x18\x01 \x03(\t2-\n\x06Ranker\x12#\n\x04Rank\x12\x0c.RankRequest\x1a\r.RankResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ranker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANKREQUEST']._serialized_start=16
  _globals['_RANKREQUEST']._serialized_end=71
  _globals['_RANKRESPONSE']._serialized_start=73
  _globals['_RANKRESPONSE']._serialized_end=107
  _globals['_RANKER']._serialized_start=109
  _globals['_RANKER']._serialized_end=154
# @@protoc_insertion_point(module_scope)
