import localFont from 'next/font/local'

import "@/app/globals.css";

export const dynamic = "force-dynamic";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="bg-gradient-to-r from-zinc-200 from-0% via-indigo-300 via-50% to-rose-200 to-100%">
      <body>{children}</body>
    </html>
  )
}
