version: '3.9'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  feature-store:
    build: ./services/feature-store
    ports:
      - "8888:8888"
    depends_on:
      - redis
    environment:
      - FEAST_USAGE=False
  web:
    build: .
    command: pnpm dev
    ports: ["3000:3000"]
    env_file: .env.local
  worker:
    build: .
    command: pnpm worker           
    env_file: .env.local
