# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedder.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'embedder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mbedder.proto\x12\x08\x65mbedder\"3\n\rUserInterests\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tinterests\x18\x02 \x03(\t\"-\n\nUserVector\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"6\n\x0c\x45mbedRequest\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.embedder.UserInterests\"1\n\nEmbedReply\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.embedder.UserVector2A\n\x08\x45mbedder\x12\x35\n\x05\x45mbed\x12\x16.embedder.EmbedRequest\x1a\x14.embedder.EmbedReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINTERESTS']._serialized_start=28
  _globals['_USERINTERESTS']._serialized_end=79
  _globals['_USERVECTOR']._serialized_start=81
  _globals['_USERVECTOR']._serialized_end=126
  _globals['_EMBEDREQUEST']._serialized_start=128
  _globals['_EMBEDREQUEST']._serialized_end=182
  _globals['_EMBEDREPLY']._serialized_start=184
  _globals['_EMBEDREPLY']._serialized_end=233
  _globals['_EMBEDDER']._serialized_start=235
  _globals['_EMBEDDER']._serialized_end=300
# @@protoc_insertion_point(module_scope)
