------------------------------------------------------------------------
-- ludics.Completeness — M4: behaviours and internal completeness
--
-- Direction 5 (mechanization), session 09 step M4 / Q-046.  This cashes the
-- §5 "internal completeness" slogan and the §2 inventory bet: the
-- biorthogonal-closure half was ALREADY built abstractly in lib.Closure
-- (`Biorthogonal`), and M3 (ludics/Separation.agda) instantiated it at the
-- real design orthogonality `_⊥_`.  M4 reads off the constitutive content
-- that instantiation now makes free:
--
--   * A BEHAVIOUR is a biorthogonally-closed set of designs (`Behaviour G =
--     clo G ≐ G`, i.e. `G = G^⊥⊥`).
--   * The CLOSURE of any set is a behaviour (`clo-behaviour`), and it is the
--     LEAST behaviour containing it (`clo-least`) — the behaviour GENERATED
--     by a set of designs.
--   * Every POLAR is a behaviour (`polar-behaviour`): the set of designs
--     passing a fixed test-set is biorthogonally closed.  Equivalently,
--     behaviours are exactly the double-polars `pol⁻ (pol⁺ G)`.
--   * INTERNAL COMPLETENESS proper (`internal-completeness`): closing a set
--     of designs does NOT change its tests — `pol⁺ (clo S) ≐ pol⁺ S`.  The
--     behaviour a set generates already contains every design the tests can
--     see; nothing new is reachable by appeal to the ambient logic.  This
--     is Girard's internal completeness, here a theorem about the real
--     `interact`-orthogonality.
--
-- Faithfulness chain: `_⊥_` is M1's `interact`-convergence (ludics.Core),
-- which M2 proved fuel-independent (so `_⊥_` is well-defined) and M3 showed
-- characterises behaviour.  So the closure here is over the SAME design
-- object the engine computes on — not a toy carrier.
--
-- Tested against: Agda 2.7.0.1, agda-stdlib v2.0.  Type-checks under
-- `--safe --without-K` WITH NO POSTULATES OR HOLES.
-- Build (from mechanisation/agda): `agda ludics/Completeness.agda`.
------------------------------------------------------------------------

{-# OPTIONS --without-K --safe #-}

module ludics.Completeness where

open import Data.List using ([]; _∷_)
open import Data.Product using (_×_; _,_; proj₁; proj₂)
open import Relation.Binary.PropositionalEquality using (_≡_; refl; sym; subst)

open import ludics.Core
open import lib.Closure using (module Biorthogonal)

------------------------------------------------------------------------
-- §1.  The biorthogonal closure at the design orthogonality `_⊥_`
--
-- Instantiate the already-built abstract `Biorthogonal` (lib.Closure §3)
-- with X = Y = Design and the design orthogonality.  `open B` brings the
-- polars, the closure `clo = pol⁻ ∘ pol⁺`, the closed predicate `Closed`,
-- and all the Galois/closure lemmas into scope.
------------------------------------------------------------------------

module B = Biorthogonal Design Design _⊥_
open B

-- The powerset operators on each side (re-bound locally; the `using ()
-- renaming` inside Biorthogonal does not re-export through `open B`).
open B.PX using () renaming (Pred to PredX; _∈_ to _∈ˣ_; _⊆_ to _⊆ˣ_; _≐_ to _≐ˣ_)
open B.PY using () renaming (Pred to PredY; _∈_ to _∈ʸ_; _⊆_ to _⊆ʸ_; _≐_ to _≐ʸ_)

------------------------------------------------------------------------
-- §2.  Behaviours = biorthogonally-closed sets of designs
--
-- A BEHAVIOUR is a set of designs equal to its own biorthogonal closure:
-- `clo G ≐ G`, i.e. `G = G^⊥⊥`.  (`_≐ˣ_` is mutual ⊆, the F2 set-equality,
-- never propositional ≡.)
------------------------------------------------------------------------

Behaviour : PredX → Set
Behaviour G = Closed G

-- A behaviour is its own double-orthogonal, in both directions.  The ⊆
-- half holds for EVERY set (closure is extensive); the ⊇ half is exactly
-- being a behaviour.
behaviour-expand : ∀ {G} → G ⊆ˣ clo G
behaviour-expand = clo-ext

behaviour-contract : ∀ {G} → Behaviour G → clo G ⊆ˣ G
behaviour-contract beh = proj₁ beh

------------------------------------------------------------------------
-- §3.  Generation: the closure is the least behaviour containing a set
------------------------------------------------------------------------

-- The biorthogonal closure of any set of designs IS a behaviour.
clo-behaviour : ∀ {S} → Behaviour (clo S)
clo-behaviour = clo-closed

-- …and it is the LEAST behaviour containing S: any behaviour above S is
-- above clo S.  So `clo S` is the behaviour GENERATED by S.
clo-least : ∀ {S G} → Behaviour G → S ⊆ˣ G → clo S ⊆ˣ G
clo-least beh S⊆G = clo-below beh S⊆G

------------------------------------------------------------------------
-- §4.  Every polar is a behaviour  (behaviours are exactly double-polars)
--
-- The set `pol⁻ T` of designs orthogonal to every test in T is always
-- biorthogonally closed.  Proof: clo (pol⁻ T) = pol⁻ (pol⁺ (pol⁻ T)), and
-- `pol⁻-antitone expand⁻` collapses the inner double-polar back to pol⁻ T;
-- the reverse inclusion is extensivity.
------------------------------------------------------------------------

polar-behaviour : ∀ {T} → Behaviour (pol⁻ T)
polar-behaviour {T} = pol⁻-antitone (expand⁻ {T}) , clo-ext

------------------------------------------------------------------------
-- §5.  Internal completeness proper
--
-- Closing a set of designs does not change the tests it passes:
--   pol⁺ (clo S) ≐ pol⁺ S.
-- The behaviour generated by S has exactly the orthogonal of S — no test
-- is gained or lost by saturating to the closure.  This is Girard's
-- internal completeness (the behaviour is "already complete from inside"),
-- delivered by the abstract `pol⁺-collapse` at the design orthogonality.
------------------------------------------------------------------------

internal-completeness : ∀ {S} → pol⁺ (clo S) ≐ʸ pol⁺ S
internal-completeness = pol⁺-collapse

------------------------------------------------------------------------
-- §6.  Non-vacuity — a concrete inhabited behaviour over real designs
--
-- `coDesigns E` = the designs orthogonal to a fixed test E.  By §4 it is a
-- behaviour; by the Core handshake it is inhabited.
------------------------------------------------------------------------

-- The singleton test-set of a design.
⟨_⟩ : Design → PredY
⟨ E ⟩ E′ = E′ ≡ E

-- Membership in a co-design behaviour from an orthogonality witness.
mem-coDesign : ∀ {D E} → D ⊥ E → (pol⁻ ⟨ E ⟩) D
mem-coDesign {D} {E} D⊥E {y} y≡E = subst (λ z → D ⊥ z) (sym y≡E) D⊥E

-- The designs orthogonal to the daimon-test (o0 ∷ dai ∷ []) form a
-- behaviour, and the Core handshake `p0 ∷ []` is one of them.
ex-behaviour : Behaviour (pol⁻ ⟨ o0 ∷ dai ∷ [] ⟩)
ex-behaviour = polar-behaviour

ex-member : (pol⁻ ⟨ o0 ∷ dai ∷ [] ⟩) (p0 ∷ [])
ex-member = mem-coDesign ex-orth
