// import "@/app/globals.css";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
// Layout shared by storefront + dashboard

import { ReactNode, Suspense } from 'react';
import { cookies } from 'next/headers';
import { prisma } from "@/lib/prismaclient";


export  async function LivePanel({ stallId }: { stallId: string }) {
  const stallIdInt = BigInt(stallId);            // Prisma model uses BigInt


  return <div><h2 className=" text-[1.37rem] font-semibold">Livestream For Stall {stallId}</h2></div>;
}
