/**
 * Phase 6 — LLM async auto-naming. Exercises the pure sanitizer and the
 * eligibility guards of `enrichDeliberationName` (flag, debounce, sticky
 * human title, insufficient content, guarded race-safe write).
 */

const prismaMock = {
  deliberation: {
    findUnique: jest.fn(),
    updateMany: jest.fn(),
  },
  claim: {
    findMany: jest.fn(),
  },
};

const redisMock = { set: jest.fn() };
const openaiCreate = jest.fn();

jest.mock("@/lib/prismaclient", () => ({ prisma: prismaMock }));
jest.mock("@/lib/upstash", () => ({
  tryGetUpstashRedis: () => redisMock,
}));
jest.mock("openai", () => {
  return {
    __esModule: true,
    default: class {
      chat = { completions: { create: openaiCreate } };
    },
  };
});

import {
  sanitizeGeneratedTitle,
  enrichDeliberationName,
  isDeliberationAutoNamingEnabled,
} from "@/lib/deliberations/autoNameEnrichment";

const ORIGINAL_ENV = { ...process.env };

beforeEach(() => {
  jest.clearAllMocks();
  process.env = { ...ORIGINAL_ENV };
  process.env.OPENAI_API_KEY = "test-key";
  process.env.DELIBERATION_LLM_AUTO_NAMING = "1";
  // Default: lock acquired.
  redisMock.set.mockResolvedValue("OK");
});

afterAll(() => {
  process.env = ORIGINAL_ENV;
});

describe("sanitizeGeneratedTitle", () => {
  it("returns null for empty input", () => {
    expect(sanitizeGeneratedTitle(null)).toBeNull();
    expect(sanitizeGeneratedTitle("")).toBeNull();
    expect(sanitizeGeneratedTitle("   ")).toBeNull();
  });

  it("strips wrapping quotes, label and trailing punctuation", () => {
    expect(sanitizeGeneratedTitle('Title: "Minimum wage effects".')).toBe(
      "Minimum wage effects",
    );
    expect(sanitizeGeneratedTitle("**Climate policy tradeoffs**")).toBe(
      "Climate policy tradeoffs",
    );
  });

  it("takes the first non-empty line and collapses whitespace", () => {
    expect(sanitizeGeneratedTitle("\n\n  Carbon   tax   debate \n more")).toBe(
      "Carbon tax debate",
    );
  });

  it("truncates overly long titles with an ellipsis", () => {
    const long = "word ".repeat(40).trim();
    const out = sanitizeGeneratedTitle(long)!;
    expect(out.length).toBeLessThanOrEqual(80);
    expect(out.endsWith("\u2026")).toBe(true);
  });
});

describe("isDeliberationAutoNamingEnabled", () => {
  it("honors the env flag", () => {
    process.env.DELIBERATION_LLM_AUTO_NAMING = "1";
    expect(isDeliberationAutoNamingEnabled()).toBe(true);
    process.env.DELIBERATION_LLM_AUTO_NAMING = "0";
    expect(isDeliberationAutoNamingEnabled()).toBe(false);
  });
});

describe("enrichDeliberationName guards", () => {
  it("short-circuits when the flag is off", async () => {
    process.env.DELIBERATION_LLM_AUTO_NAMING = "0";
    const res = await enrichDeliberationName("d1");
    expect(res).toEqual({ updated: false, reason: "flag_off" });
    expect(prismaMock.deliberation.findUnique).not.toHaveBeenCalled();
  });

  it("debounces when the lock is already held", async () => {
    redisMock.set.mockResolvedValueOnce(null);
    const res = await enrichDeliberationName("d1");
    expect(res).toEqual({ updated: false, reason: "debounced" });
    expect(prismaMock.deliberation.findUnique).not.toHaveBeenCalled();
  });

  it("never overwrites a sticky human title", async () => {
    prismaMock.deliberation.findUnique.mockResolvedValue({
      id: "d1",
      title: "Human Chosen",
      titleAutoGenerated: false,
    });
    const res = await enrichDeliberationName("d1");
    expect(res).toEqual({ updated: false, reason: "human_title" });
    expect(prismaMock.claim.findMany).not.toHaveBeenCalled();
    expect(prismaMock.deliberation.updateMany).not.toHaveBeenCalled();
  });

  it("skips when there is insufficient content", async () => {
    prismaMock.deliberation.findUnique.mockResolvedValue({
      id: "d1",
      title: null,
      titleAutoGenerated: false,
    });
    prismaMock.claim.findMany.mockResolvedValue([{ text: "only one" }]);
    const res = await enrichDeliberationName("d1");
    expect(res).toEqual({ updated: false, reason: "insufficient_content" });
    expect(openaiCreate).not.toHaveBeenCalled();
  });

  it("generates and persists a title via a guarded updateMany", async () => {
    prismaMock.deliberation.findUnique.mockResolvedValue({
      id: "d1",
      title: null,
      titleAutoGenerated: false,
    });
    prismaMock.claim.findMany.mockResolvedValue([
      { text: "Minimum wage raises unemployment" },
      { text: "Minimum wage reduces poverty" },
      { text: "Elasticity estimates vary widely" },
    ]);
    openaiCreate.mockResolvedValue({
      choices: [{ message: { content: '"Minimum wage tradeoffs"' } }],
    });
    prismaMock.deliberation.updateMany.mockResolvedValue({ count: 1 });

    const res = await enrichDeliberationName("d1");
    expect(res.updated).toBe(true);
    expect(res.reason).toBe("updated");
    expect(res.title).toBe("Minimum wage tradeoffs");

    const writeArg = prismaMock.deliberation.updateMany.mock.calls[0][0];
    expect(writeArg.where.id).toBe("d1");
    expect(writeArg.where.OR).toEqual([
      { titleAutoGenerated: true },
      { title: null },
    ]);
    expect(writeArg.data.title).toBe("Minimum wage tradeoffs");
    expect(writeArg.data.titleAutoGenerated).toBe(true);
    expect(writeArg.data.titleUpdatedAt).toBeInstanceOf(Date);
  });

  it("reports raced_human_title when the guarded write matches no rows", async () => {
    prismaMock.deliberation.findUnique.mockResolvedValue({
      id: "d1",
      title: "auto placeholder",
      titleAutoGenerated: true,
    });
    prismaMock.claim.findMany.mockResolvedValue([
      { text: "a" },
      { text: "b" },
      { text: "c" },
    ]);
    openaiCreate.mockResolvedValue({
      choices: [{ message: { content: "Some title" } }],
    });
    prismaMock.deliberation.updateMany.mockResolvedValue({ count: 0 });

    const res = await enrichDeliberationName("d1");
    expect(res).toEqual({ updated: false, reason: "raced_human_title" });
  });

  it("falls back to the first claim when the LLM yields nothing", async () => {
    prismaMock.deliberation.findUnique.mockResolvedValue({
      id: "d1",
      title: null,
      titleAutoGenerated: true,
    });
    prismaMock.claim.findMany.mockResolvedValue([
      { text: "Fallback claim text" },
      { text: "b" },
      { text: "c" },
    ]);
    openaiCreate.mockResolvedValue({
      choices: [{ message: { content: "   " } }],
    });
    prismaMock.deliberation.updateMany.mockResolvedValue({ count: 1 });

    const res = await enrichDeliberationName("d1");
    expect(res.updated).toBe(true);
    expect(res.title).toBe("Fallback claim text");
  });
});
