import {
  resolveDeliberationName,
  deriveAutoTitleFromClaim,
  defaultHostName,
  DEFAULT_DELIBERATION_NAME,
} from "@/lib/deliberations/resolveName";

describe("resolveDeliberationName precedence", () => {
  it("1. prefers a human title over everything", () => {
    expect(
      resolveDeliberationName(
        { title: "Human Name", titleAutoGenerated: false },
        { hostName: "Article Title", firstClaimText: "some claim" },
      ),
    ).toBe("Human Name");
  });

  it("1. human title wins even when titleAutoGenerated is undefined", () => {
    expect(
      resolveDeliberationName(
        { title: "Human Name" },
        { hostName: "Article Title" },
      ),
    ).toBe("Human Name");
  });

  it("2. falls back to host name when no human title", () => {
    expect(
      resolveDeliberationName(
        { title: null, titleAutoGenerated: false },
        { hostName: "Article Title", firstClaimText: "some claim" },
      ),
    ).toBe("Article Title");
  });

  it("2. host name beats an auto-generated title", () => {
    expect(
      resolveDeliberationName(
        { title: "Auto Placeholder", titleAutoGenerated: true },
        { hostName: "Article Title" },
      ),
    ).toBe("Article Title");
  });

  it("3. uses auto-generated title when no human title and no host name", () => {
    expect(
      resolveDeliberationName(
        { title: "Auto Placeholder", titleAutoGenerated: true },
        { firstClaimText: "some claim" },
      ),
    ).toBe("Auto Placeholder");
  });

  it("4. derives from first claim text when nothing else is available", () => {
    expect(
      resolveDeliberationName(
        { title: null, titleAutoGenerated: false },
        { firstClaimText: "Caffeine improves focus" },
      ),
    ).toBe("Caffeine improves focus");
  });

  it("4. uses the default fallback when there is nothing at all", () => {
    expect(resolveDeliberationName({})).toBe(DEFAULT_DELIBERATION_NAME);
  });

  it("4. respects a custom fallback override", () => {
    expect(
      resolveDeliberationName({}, { fallback: "Custom Fallback" }),
    ).toBe("Custom Fallback");
  });

  it("treats whitespace-only title as absent", () => {
    expect(
      resolveDeliberationName(
        { title: "   ", titleAutoGenerated: false },
        { hostName: "Article Title" },
      ),
    ).toBe("Article Title");
  });

  it("treats whitespace-only host name as absent", () => {
    expect(
      resolveDeliberationName(
        { title: null },
        { hostName: "  ", firstClaimText: "A claim" },
      ),
    ).toBe("A claim");
  });
});

describe("deriveAutoTitleFromClaim", () => {
  it("returns null for empty/nullish input", () => {
    expect(deriveAutoTitleFromClaim(null)).toBeNull();
    expect(deriveAutoTitleFromClaim(undefined)).toBeNull();
    expect(deriveAutoTitleFromClaim("   ")).toBeNull();
  });

  it("collapses whitespace and trims", () => {
    expect(deriveAutoTitleFromClaim("  hello   world  ")).toBe("hello world");
  });

  it("truncates long text with an ellipsis", () => {
    const long = "a".repeat(120);
    const result = deriveAutoTitleFromClaim(long, 80);
    expect(result).toHaveLength(80);
    expect(result?.endsWith("\u2026")).toBe(true);
  });

  it("leaves short text intact", () => {
    expect(deriveAutoTitleFromClaim("short claim", 80)).toBe("short claim");
  });
});

describe("defaultHostName", () => {
  it("names the My Arguments standalone deliberation", () => {
    expect(
      defaultHostName("free", "standalone-my-arguments-user_123"),
    ).toBe("My Arguments");
  });

  it("returns null for other free host ids", () => {
    expect(defaultHostName("free", "something-else")).toBeNull();
  });

  it("returns null for host types with a rich host object", () => {
    expect(defaultHostName("article", "article_42")).toBeNull();
  });
});
