import '@/app/globals.css';
import '@/app/article.templates.css';   // <— single import
// import './article.global.scss';
import '@/app/fonts/fonts.css';
import "@/app/article/type-tokens.css";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
