"use client";

import { useEffect, useRef, useState } from "react";
import useSWR from "swr";
import { Check, Pencil, X } from "lucide-react";

type DeliberationGetResponse = {
  id: string;
  hostType: string;
  hostId: string;
  title: string | null;
  titleAutoGenerated: boolean;
  createdById: string | null;
  displayName: string;
  /**
   * Server-computed: whether the requesting user may rename (deliberation
   * creator OR host-object owner, e.g. the article author). Authoritative —
   * do not re-derive from `createdById` on the client, which is unreliable
   * for host-bound deliberations.
   */
  canRename?: boolean;
};

const fetcher = (url: string) =>
  fetch(url).then((r) => (r.ok ? r.json() : Promise.reject(r)));

const MAX_TITLE_LENGTH = 200;

/**
 * Deliberation header title with inline rename.
 *
 * Renders the resolved display name. The deliberation creator gets an inline
 * editor (pencil) that PATCHes `/api/deliberations/[id]`. Non-hosts and
 * signed-out users see a read-only heading.
 *
 * When no human title is set, falls back to the existing
 * `Deliberation for "hostName"` framing so unnamed deliberations look unchanged.
 */
export default function DeliberationTitle({
  deliberationId,
  hostName,
}: {
  deliberationId: string;
  hostName?: string | null;
}) {
  const swrKey = `/api/deliberations/${deliberationId}`;
  const { data, mutate } = useSWR<DeliberationGetResponse>(swrKey, fetcher);

  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const hasHumanTitle =
    !!data && data.titleAutoGenerated === false && !!data.title;

  const heading = hasHumanTitle
    ? (data!.title as string)
    : hostName
      ? `Deliberation for "${hostName}"`
      : data?.displayName ?? "Deliberation";

  const isHost = data?.canRename === true;

  useEffect(() => {
    if (editing) inputRef.current?.focus();
  }, [editing]);

  function startEditing() {
    setDraft(data?.title ?? "");
    setError(null);
    setEditing(true);
  }

  function cancel() {
    setEditing(false);
    setError(null);
  }

  async function save() {
    if (saving) return;
    setSaving(true);
    setError(null);
    const next = draft.trim();
    try {
      const res = await fetch(swrKey, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: next.length ? next : null }),
      });
      if (!res.ok) {
        throw new Error("Could not save name");
      }
      const updated = (await res.json()) as DeliberationGetResponse;
      await mutate(updated, { revalidate: false });
      setEditing(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not save name");
    } finally {
      setSaving(false);
    }
  }

  function onKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") {
      e.preventDefault();
      void save();
    } else if (e.key === "Escape") {
      e.preventDefault();
      cancel();
    }
  }

  if (editing) {
    return (
      <div className="w-full">
        <div className="flex items-center justify-center gap-2 mb-4">
          <input
            ref={inputRef}
            value={draft}
            maxLength={MAX_TITLE_LENGTH}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={onKeyDown}
            disabled={saving}
            placeholder="Name this deliberation"
            className="w-[60%] max-w-[640px] rounded-md border border-slate-400/60 bg-white/70 px-3 py-2 text-center text-2xl font-[Kolonia] uppercase tracking-wide text-slate-800 focus:outline-none focus:ring-2 focus:ring-slate-400"
          />
          <button
            type="button"
            onClick={() => void save()}
            disabled={saving}
            title="Save"
            aria-label="Save name"
            className="rounded-md p-1.5 text-slate-600 hover:bg-slate-200/60 disabled:opacity-50"
          >
            <Check className="h-5 w-5" />
          </button>
          <button
            type="button"
            onClick={cancel}
            disabled={saving}
            title="Cancel"
            aria-label="Cancel rename"
            className="rounded-md p-1.5 text-slate-600 hover:bg-slate-200/60 disabled:opacity-50"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
        {error && (
          <p className="text-center text-sm text-red-500 mb-2">{error}</p>
        )}
        <div className="mx-auto w-[80%] border-b border-slate-500/40" />
      </div>
    );
  }

  return (
    <div className="w-full">
      <div className="group flex items-center justify-center gap-2 mb-4">
        <h2 className="text-4xl font-[Kolonia] uppercase tracking-wide text-center text-slate-800">
          {heading}
        </h2>
        {isHost && (
          <button
            type="button"
            onClick={startEditing}
            title="Rename deliberation"
            aria-label="Rename deliberation"
            className="rounded-md p-1.5 text-slate-400 opacity-0 transition-opacity hover:bg-slate-200/60 hover:text-slate-700 group-hover:opacity-100"
          >
            <Pencil className="h-4 w-4" />
          </button>
        )}
      </div>
      <div className="mx-auto w-[80%] border-b border-slate-500/40" />
    </div>
  );
}
