apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-store
  template:
    metadata:
      labels:
        app: feature-store
    spec:
      containers:
        - name: feature-store
          image: feature-store:latest
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
