/**
 * lib/deliberations/autoNameEnrichment.ts
 *
 * Phase 6 of the deliberation-naming roadmap (§5 "LLM enrichment", §9):
 * asynchronous LLM auto-naming.
 *
 * Once enough content has landed in a deliberation we generate a concise
 * summary title and persist it — but ONLY for rows whose title is still
 * auto-generated (or `NULL`). A human-set title (`titleAutoGenerated === false`
 * with non-empty text) is sticky and is never touched, including against a
 * concurrent rename (the final write is a guarded `updateMany`).
 *
 * Mirrors the fire-and-forget provenance-enrichment pattern in
 * `lib/citations/evidenceProvenance.ts`:
 *   - never throws to the caller;
 *   - detached from the request lifetime via `void`/`.catch`;
 *   - gated on a feature flag (env + per-deliberation overrides);
 *   - degrades gracefully when OpenAI / Upstash are not configured.
 *
 * See docs/DELIBERATION_NAMING_ROADMAP.md §5, §9.
 */

import OpenAI from "openai";
import { prisma } from "@/lib/prismaclient";
import { tryGetUpstashRedis } from "@/lib/upstash";
import { deriveAutoTitleFromClaim } from "@/lib/deliberations/resolveName";

// ============================================================
// Tunables
// ============================================================

/** Don't bother naming a near-empty deliberation. */
const MIN_CLAIMS = 3;
/** Claim texts fed to the model as naming context. */
const MAX_CONTEXT_CLAIMS = 12;
/** Hard cap on a generated title (chars). */
const MAX_TITLE_LENGTH = 80;
/**
 * Debounce window. Argument creation can fire this many times in quick
 * succession; one LLM pass per deliberation per window is plenty.
 */
const DEBOUNCE_TTL_SECONDS = 10 * 60;
const MODEL_ID = "gpt-4o-mini";

// ============================================================
// Feature flag
// ============================================================

/**
 * Per-deliberation overrides (e.g. dogfood a single room). Populated at
 * process start from `DELIBERATION_LLM_AUTO_NAMING_DELIBERATIONS`
 * (comma-separated `<id>=on|off` pairs). Mirrors the chain-essay-polish flag.
 */
const NAMING_OVERRIDES: Map<string, boolean> = (() => {
  const raw = process.env.DELIBERATION_LLM_AUTO_NAMING_DELIBERATIONS ?? "";
  const out = new Map<string, boolean>();
  for (const pair of raw.split(",")) {
    const [id, val] = pair.split("=").map((s) => s.trim());
    if (!id) continue;
    out.set(id, val === "on" || val === "1" || val === "true");
  }
  return out;
})();

export function isDeliberationAutoNamingEnabled(opts?: {
  deliberationId?: string | null;
}): boolean {
  const id = opts?.deliberationId ?? null;
  if (id && NAMING_OVERRIDES.has(id)) return NAMING_OVERRIDES.get(id) === true;
  const env = process.env.DELIBERATION_LLM_AUTO_NAMING;
  return env === "1" || env === "true" || env === "on";
}

// ============================================================
// LLM client (lazy)
// ============================================================

let _openai: OpenAI | null = null;
function getOpenAI(): OpenAI | null {
  if (_openai) return _openai;
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return null;
  _openai = new OpenAI({ apiKey });
  return _openai;
}

// ============================================================
// Helpers
// ============================================================

/**
 * Normalize a raw LLM title: first non-empty line, strip surrounding
 * quotes / markdown emphasis, collapse whitespace, drop trailing
 * punctuation, then truncate to `MAX_TITLE_LENGTH` with an ellipsis.
 * Returns `null` when nothing usable remains.
 */
export function sanitizeGeneratedTitle(raw: string | null | undefined): string | null {
  if (!raw) return null;
  let t = raw.split("\n").map((l) => l.trim()).find((l) => l.length > 0) ?? "";
  // Strip a leading label the model sometimes adds ("Title: ...").
  t = t.replace(/^title\s*[:\-]\s*/i, "");
  // Strip wrapping quotes / backticks / asterisks and trailing sentence
  // punctuation. Both ends are cleaned together so `"…".` loses the quote and
  // the period regardless of order.
  t = t.replace(/^["'`*\s]+/, "").replace(/["'`*.,;:\s]+$/, "").trim();
  return deriveAutoTitleFromClaim(t, MAX_TITLE_LENGTH);
}

async function generateTitleFromClaims(claimTexts: string[]): Promise<string | null> {
  const openai = getOpenAI();
  if (!openai) return null;
  const bullets = claimTexts
    .map((t) => `- ${t.replace(/\s+/g, " ").trim()}`)
    .join("\n");
  const prompt = [
    "You are titling a deliberation: a structured map of arguments and claims.",
    "Write one concise, neutral title that captures the central question or topic.",
    "Rules: at most 8 words; no quotation marks; no trailing punctuation;",
    "do not take a side; title case is not required.",
    "",
    "Claims in the deliberation:",
    bullets,
    "",
    "Title:",
  ].join("\n");

  try {
    const completion = await openai.chat.completions.create({
      model: MODEL_ID,
      messages: [{ role: "user", content: prompt }],
      temperature: 0.3,
      max_tokens: 32,
    });
    return sanitizeGeneratedTitle(completion.choices[0]?.message?.content ?? null);
  } catch (err) {
    console.error("[autoNameEnrichment] LLM call failed", err);
    return null;
  }
}

type EnrichResult = {
  updated: boolean;
  reason:
    | "flag_off"
    | "debounced"
    | "not_found"
    | "human_title"
    | "insufficient_content"
    | "llm_unavailable"
    | "raced_human_title"
    | "updated";
  title?: string;
};

/**
 * Generate and persist an auto-title for a deliberation, if eligible.
 * Idempotent-ish and self-debouncing; never throws.
 *
 * Eligibility (all must hold):
 *   - feature flag on (or `force`);
 *   - not debounced within `DEBOUNCE_TTL_SECONDS` (skipped when `force`);
 *   - the deliberation exists;
 *   - its title is not a sticky human title;
 *   - it has at least `MIN_CLAIMS` claims.
 *
 * The final write is a guarded `updateMany` (only rows still
 * `titleAutoGenerated === true` or `title === null`), so a human rename that
 * races the LLM pass always wins.
 */
export async function enrichDeliberationName(
  deliberationId: string,
  opts: { force?: boolean } = {},
): Promise<EnrichResult> {
  const force = opts.force === true;
  if (!force && !isDeliberationAutoNamingEnabled({ deliberationId })) {
    return { updated: false, reason: "flag_off" };
  }

  // Debounce: one LLM pass per deliberation per window. Best-effort — when
  // Upstash is absent we simply skip the lock (dev/CI), relying on the flag.
  if (!force) {
    const redis = tryGetUpstashRedis();
    if (redis) {
      try {
        const lockKey = `delib:autoname:lock:${deliberationId}`;
        const acquired = await redis.set(lockKey, "1", {
          nx: true,
          ex: DEBOUNCE_TTL_SECONDS,
        });
        if (acquired !== "OK") {
          return { updated: false, reason: "debounced" };
        }
      } catch {
        /* lock failures must not block naming */
      }
    }
  }

  const deliberation = await prisma.deliberation.findUnique({
    where: { id: deliberationId },
    select: { id: true, title: true, titleAutoGenerated: true },
  });
  if (!deliberation) return { updated: false, reason: "not_found" };

  const hasHumanTitle =
    !!deliberation.title?.trim() && deliberation.titleAutoGenerated === false;
  if (hasHumanTitle) return { updated: false, reason: "human_title" };

  const claims = await prisma.claim.findMany({
    where: { deliberationId },
    select: { text: true },
    orderBy: { createdAt: "asc" },
    take: MAX_CONTEXT_CLAIMS,
  });
  const claimTexts = claims
    .map((c) => c.text?.trim())
    .filter((t): t is string => !!t);
  if (claimTexts.length < MIN_CLAIMS) {
    return { updated: false, reason: "insufficient_content" };
  }

  const title =
    (await generateTitleFromClaims(claimTexts)) ??
    deriveAutoTitleFromClaim(claimTexts[0], MAX_TITLE_LENGTH);
  if (!title) return { updated: false, reason: "llm_unavailable" };

  // Guarded write: never clobber a human title set in the meantime.
  const result = await prisma.deliberation.updateMany({
    where: {
      id: deliberationId,
      OR: [{ titleAutoGenerated: true }, { title: null }],
    },
    data: {
      title,
      titleAutoGenerated: true,
      titleUpdatedAt: new Date(),
    },
  });
  if (result.count === 0) {
    return { updated: false, reason: "raced_human_title" };
  }
  return { updated: true, reason: "updated", title };
}

/**
 * Fire-and-forget wrapper. Detaches from the request lifetime and swallows
 * all errors — safe to call from a route handler after the response payload
 * has been assembled.
 */
export function enrichDeliberationNameInBackground(
  deliberationId: string | null | undefined,
  opts: { force?: boolean } = {},
): void {
  if (!deliberationId) return;
  void enrichDeliberationName(deliberationId, opts).catch(() => {});
}
