import type { DeliberationHostType } from "@prisma/client";

/**
 * Canonical deliberation-name resolution.
 *
 * Replaces the ~8 ad-hoc title fallbacks scattered across the codebase
 * ("Untitled Deliberation", "Deliberation", truncated id, host name, silent)
 * with one deterministic precedence:
 *
 *   1. Human title       — `title` set AND `titleAutoGenerated === false`
 *   2. Host-derived name  — article.title / room.title / discussion topic / "My Arguments"
 *   3. Auto-generated     — `title` set AND `titleAutoGenerated === true`
 *   4. Fallback           — derived from first conclusion claim text, else `"Untitled deliberation"`
 *
 * The resolver is pure/synchronous. Callers are responsible for fetching the
 * host-derived name and (optionally) the first-claim text, since those require
 * DB access; the resolver only applies precedence.
 *
 * See docs/DELIBERATION_NAMING_ROADMAP.md §4.
 */

export const DEFAULT_DELIBERATION_NAME = "Untitled deliberation";

/** Minimal shape needed from a Deliberation row to resolve its name. */
export type DeliberationNameInput = {
  title?: string | null;
  titleAutoGenerated?: boolean | null;
};

export type ResolveDeliberationNameOptions = {
  /** Host-derived name (e.g. article.title, room.title, discussion topic, "My Arguments"). */
  hostName?: string | null;
  /** First conclusion claim text, used to build the deterministic fallback. */
  firstClaimText?: string | null;
  /** Override the final fallback string. */
  fallback?: string;
};

function clean(value: string | null | undefined): string | null {
  if (value == null) return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

/**
 * Build a deterministic auto-title from a claim's text: trimmed, collapsed
 * whitespace, and truncated to a reasonable length with an ellipsis.
 */
export function deriveAutoTitleFromClaim(
  claimText: string | null | undefined,
  maxLength = 80,
): string | null {
  const normalized = clean(claimText?.replace(/\s+/g, " "));
  if (!normalized) return null;
  if (normalized.length <= maxLength) return normalized;
  return `${normalized.slice(0, maxLength - 1).trimEnd()}\u2026`;
}

/**
 * Resolve the display name for a deliberation using the canonical precedence.
 * Always returns a non-empty string.
 */
export function resolveDeliberationName(
  deliberation: DeliberationNameInput,
  opts: ResolveDeliberationNameOptions = {},
): string {
  const title = clean(deliberation.title);
  const isAutoGenerated = deliberation.titleAutoGenerated === true;

  // 1. Human title — explicitly set, not auto-generated.
  if (title && !isAutoGenerated) return title;

  // 2. Host-derived name.
  const hostName = clean(opts.hostName);
  if (hostName) return hostName;

  // 3. Auto-generated title.
  if (title && isAutoGenerated) return title;

  // 4. Deterministic fallback from first claim, else the default.
  const fromClaim = deriveAutoTitleFromClaim(opts.firstClaimText);
  if (fromClaim) return fromClaim;

  return opts.fallback ?? DEFAULT_DELIBERATION_NAME;
}

/**
 * Default host-derived name for host types that have a natural standalone name
 * but no rich host object to borrow from. Returns `null` when the host type
 * has no inherent name (caller should supply `hostName` from the host object).
 */
export function defaultHostName(
  hostType: DeliberationHostType,
  hostId: string,
): string | null {
  if (hostType === "free" && hostId.startsWith("standalone-my-arguments-")) {
    return "My Arguments";
  }
  return null;
}
