// app/api/deliberations/[id]/route.ts
import { NextResponse,NextRequest } from 'next/server';
import { prisma } from '@/lib/prismaclient';
import { getUserFromCookies, getCurrentUserId } from "@/lib/serverutils";
import { emitBus } from "@/lib/server/bus";
import { z } from "zod";
import {
  resolveDeliberationName,
  defaultHostName,
} from "@/lib/deliberations/resolveName";

export const dynamic = 'force-dynamic';

const MAX_TITLE_LENGTH = 200;


export async function GET(_req: Request, { params }:{ params:{ id:string }}) {
  const d = await prisma.deliberation.findUnique({
    where: { id: params.id },
    select: {
      id: true,
      hostType: true,
      hostId: true,
      title: true,
      titleAutoGenerated: true,
      createdById: true,
    },
  });
  if (!d) return NextResponse.json({ error:'not found' }, { status:404 });

  const displayName = resolveDeliberationName(d, {
    hostName: defaultHostName(d.hostType, d.hostId),
  });

  return NextResponse.json({ ...d, displayName });
}

const PatchBody = z.object({
  // `null`/empty string clears the human title, reverting to auto/host name.
  title: z.string().max(MAX_TITLE_LENGTH).nullable().optional(),
});

export async function PATCH(req: NextRequest, { params }: { params: { id: string } }) {
  const userId = await getCurrentUserId();
  if (!userId) {
    return NextResponse.json({ error: "Unauthenticated" }, { status: 401 });
  }

  const parsed = PatchBody.safeParse(await req.json().catch(() => null));
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }

  const existing = await prisma.deliberation.findUnique({
    where: { id: params.id },
    select: { id: true, createdById: true, hostType: true, hostId: true },
  });
  if (!existing) {
    return NextResponse.json({ error: "not found" }, { status: 404 });
  }

  // Auth: only the deliberation creator may rename (host-admin convention:
  // `createdById` is the stringified internal User.id — see lib/pathways/auth.ts).
  if (existing.createdById !== String(userId)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const rawTitle = parsed.data.title;
  const trimmed = typeof rawTitle === "string" ? rawTitle.trim() : rawTitle;

  // Empty/whitespace or explicit null => clear the human title (revert to auto).
  const clearing = trimmed == null || trimmed === "";

  const updated = await prisma.deliberation.update({
    where: { id: params.id },
    data: clearing
      ? { title: null, titleAutoGenerated: false, titleUpdatedAt: new Date() }
      : { title: trimmed, titleAutoGenerated: false, titleUpdatedAt: new Date() },
    select: {
      id: true,
      hostType: true,
      hostId: true,
      title: true,
      titleAutoGenerated: true,
      createdById: true,
    },
  });

  const displayName = resolveDeliberationName(updated, {
    hostName: defaultHostName(updated.hostType, updated.hostId),
  });

  emitBus("deliberations:created", { id: params.id }); // nudge hub to refresh

  return NextResponse.json({ ...updated, displayName });
}

export async function DELETE(_: NextRequest, { params }: { params: { id: string } }) {
  const user = await getUserFromCookies();
  if (!user) return NextResponse.json({ error: "Unauthenticated" }, { status: 401 });

  // soft-archive — add a status field in schema if you want hard delete
  await prisma.deliberation.update({
    where: { id: params.id, createdById: String(user.userId) } as any,
    data: { updatedAt: new Date() }, // noop; replace with status: 'archived'
  }).catch(()=>{});

  emitBus("deliberations:created", { id: params.id }); // nudge hub to refresh
  return NextResponse.json({ ok: true });
}