export const dynamic = "force-dynamic";

// app/api/deliberations/create/route.ts
//
// From-scratch deliberation creation (docs/DELIBERATION_CREATION_DEV_SPEC.md §3.1).
//
// This is the THIRD, intentionally distinct create entry point. Do NOT overload:
//   - `ensure`  (host-attached, idempotent on [hostType, hostId])  → ensure/route.ts
//   - `spawn`   (article → AgoraRoom → DebateSheet chain)           → spawn/route.ts
//   - `create`  (this file: standalone, hostType `free`)
//
// `hostType: free` is the seamless default for a standalone deliberation: `free`
// has no `resolveHostOwnerId` host-owner (lib/deliberations/ownership.ts), so
// `createdById` is the sole host-owner signal — exactly what a from-scratch
// deliberation wants — and it is never read at eval time. `hostId` is set
// self-referentially to the deliberation's own id, so every scratch create is
// globally unique (no [hostType, hostId] collisions).
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prismaclient";
import { getCurrentUserId } from "@/lib/serverutils";
import { emitBus } from "@/lib/server/bus";
import { jsonSafe } from "@/lib/bigintjson";
import { ensureBaselineLudicsDesigns } from "@/lib/ludics/ensureBaseline";
import { onDeliberationCreated } from "@/lib/triggers/knowledgeGraphTriggers";
import { DELIBERATION_GOVERNANCE_ROLES } from "@/lib/deliberations/governance";
import { z } from "zod";

const Body = z.object({
  title: z.string().trim().min(1).max(200),
  visibility: z.enum(["public", "unlisted", "private"]).default("public"),
  moderatorIds: z.array(z.string().min(1)).optional(),
  tags: z.array(z.string()).optional(),
});

export async function POST(req: NextRequest) {
  const me = await getCurrentUserId();
  if (!me) return NextResponse.json({ error: "Unauthenticated" }, { status: 401 });

  const parsed = Body.safeParse(await req.json().catch(() => null));
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }
  const { title, visibility, moderatorIds = [], tags = [] } = parsed.data;
  const creator = String(me);

  // Self-referential hostId: create with a placeholder, then point hostId at the
  // row's own (globally unique) cuid. Keeps `free` scratch creates collision-free.
  const created = await prisma.deliberation.create({
    data: {
      hostType: "free",
      hostId: "pending",
      createdById: creator,
      title,
      titleAutoGenerated: false,
      visibility,
      tags,
    },
    select: { id: true },
  });
  const d = await prisma.deliberation.update({
    where: { id: created.id },
    data: { hostId: created.id },
    select: { id: true },
  });

  // Governance roles: creator → owner; each moderator → moderator. De-dupe and
  // never grant the creator a redundant moderator row.
  const moderatorSet = new Set(
    moderatorIds.map(String).filter((id) => id && id !== creator),
  );
  const roleRows = [
    { deliberationId: d.id, userId: creator, role: DELIBERATION_GOVERNANCE_ROLES.OWNER, invitedById: creator },
    ...[...moderatorSet].map((userId) => ({
      deliberationId: d.id,
      userId,
      role: DELIBERATION_GOVERNANCE_ROLES.MODERATOR,
      invitedById: creator,
    })),
  ];
  await prisma.deliberationRole.createMany({ data: roleRows, skipDuplicates: true });

  // Shared post-create side-effects (mirror `ensure`): bus, KG trigger, Ludics
  // baseline. TODO(§3.1): factor these out of ensure/spawn/create into one helper.
  emitBus("deliberations:created", {
    id: d.id,
    hostType: "free",
    hostId: d.id,
    visibility,
    source: "create",
  });
  onDeliberationCreated(d.id).catch(console.error);
  try {
    await ensureBaselineLudicsDesigns({
      deliberationId: d.id,
      participantId: creator,
      seedActs: true,
    });
  } catch (e) {
    console.warn("[ludics] baseline seed failed:", e);
  }

  return NextResponse.json(
    jsonSafe({ ok: true, id: d.id, visibility, redirect: `/deliberation/${d.id}` }),
  );
}
