/**
 * From-scratch deliberation creation
 * (docs/DELIBERATION_CREATION_DEV_SPEC.md §7).
 *
 * Covers:
 *   • POST /api/deliberations/create sets hostType `free`, explicit title,
 *     titleAutoGenerated:false, default visibility `public`, self-referential
 *     hostId; seeds the creator as `owner` and each moderator as `moderator`.
 *   • visibility default + override.
 *   • the `isModerator` governance helper.
 */

// ── Side-effect modules stubbed so the test stays on creation semantics. ──
jest.mock("@/lib/serverutils", () => ({
  getCurrentUserId: jest.fn(async () => "u-creator"),
}));
jest.mock("@/lib/server/bus", () => ({ emitBus: jest.fn() }));
jest.mock("@/lib/ludics/ensureBaseline", () => ({
  ensureBaselineLudicsDesigns: jest.fn(async () => ({ proId: "p", oppId: "o" })),
}));
jest.mock("@/lib/triggers/knowledgeGraphTriggers", () => ({
  onDeliberationCreated: jest.fn(async () => undefined),
}));

jest.mock("@/lib/prismaclient", () => {
  const deliberation = {
    create: jest.fn(),
    update: jest.fn(),
    findUnique: jest.fn(),
  };
  const deliberationRole = {
    createMany: jest.fn(async () => ({ count: 0 })),
    findMany: jest.fn(async () => []),
  };
  return { prisma: { deliberation, deliberationRole } };
});

import { prisma } from "@/lib/prismaclient";
import { emitBus } from "@/lib/server/bus";
import { getCurrentUserId } from "@/lib/serverutils";
import { POST } from "@/app/api/deliberations/create/route";
import { isModerator } from "@/lib/deliberations/governance";

const prismaAny = prisma as any;

function reqWith(body: unknown) {
  return { json: async () => body } as any;
}

beforeEach(() => {
  jest.clearAllMocks();
  (getCurrentUserId as jest.Mock).mockResolvedValue("u-creator");
  prismaAny.deliberation.create.mockResolvedValue({ id: "delib-1" });
  prismaAny.deliberation.update.mockResolvedValue({ id: "delib-1" });
  prismaAny.deliberationRole.createMany.mockResolvedValue({ count: 1 });
});

describe("POST /api/deliberations/create", () => {
  it("creates a free-host, explicitly-titled, public deliberation", async () => {
    const res = await POST(reqWith({ title: "  Should we ship?  " }));
    const json = await res.json();

    expect(res.status).toBe(200);
    expect(json.ok).toBe(true);
    expect(json.id).toBe("delib-1");
    expect(json.redirect).toBe("/deliberation/delib-1");

    const createArgs = prismaAny.deliberation.create.mock.calls[0][0];
    expect(createArgs.data.hostType).toBe("free");
    expect(createArgs.data.title).toBe("Should we ship?");
    expect(createArgs.data.titleAutoGenerated).toBe(false);
    expect(createArgs.data.visibility).toBe("public");
    expect(createArgs.data.createdById).toBe("u-creator");

    // hostId is patched to the row's own id (self-referential).
    const updateArgs = prismaAny.deliberation.update.mock.calls[0][0];
    expect(updateArgs.data.hostId).toBe("delib-1");
  });

  it("honours an explicit visibility override", async () => {
    await POST(reqWith({ title: "Private topic", visibility: "private" }));
    const createArgs = prismaAny.deliberation.create.mock.calls[0][0];
    expect(createArgs.data.visibility).toBe("private");
  });

  it("seeds creator as owner and each moderator as moderator (de-duped)", async () => {
    await POST(
      reqWith({
        title: "Governed",
        moderatorIds: ["u-mod-a", "u-mod-b", "u-creator", "u-mod-a"],
      }),
    );
    const rows = prismaAny.deliberationRole.createMany.mock.calls[0][0].data;
    const owner = rows.filter((r: any) => r.role === "owner");
    const mods = rows.filter((r: any) => r.role === "moderator");

    expect(owner).toHaveLength(1);
    expect(owner[0].userId).toBe("u-creator");
    expect(mods.map((m: any) => m.userId).sort()).toEqual(["u-mod-a", "u-mod-b"]);
    // creator is never granted a redundant moderator row
    expect(mods.some((m: any) => m.userId === "u-creator")).toBe(false);
  });

  it("emits deliberations:created with source=create and visibility", async () => {
    await POST(reqWith({ title: "Eventful", visibility: "unlisted" }));
    expect(emitBus).toHaveBeenCalledWith(
      "deliberations:created",
      expect.objectContaining({ id: "delib-1", source: "create", visibility: "unlisted", hostType: "free" }),
    );
  });

  it("rejects an empty title", async () => {
    const res = await POST(reqWith({ title: "   " }));
    expect(res.status).toBe(400);
    expect(prismaAny.deliberation.create).not.toHaveBeenCalled();
  });

  it("401s when unauthenticated", async () => {
    (getCurrentUserId as jest.Mock).mockResolvedValueOnce(null);
    const res = await POST(reqWith({ title: "Anon" }));
    expect(res.status).toBe(401);
  });
});

describe("isModerator", () => {
  it("is true for the deliberation creator", async () => {
    prismaAny.deliberation.findUnique.mockResolvedValue({ createdById: "u-creator" });
    await expect(isModerator("delib-1", "u-creator")).resolves.toBe(true);
  });

  it("is true for an owner/moderator role holder", async () => {
    prismaAny.deliberation.findUnique.mockResolvedValue({ createdById: "someone-else" });
    prismaAny.deliberationRole.findMany.mockResolvedValue([{ role: "Moderator" }]);
    await expect(isModerator("delib-1", "u-mod")).resolves.toBe(true);
  });

  it("is false for a non-governance role holder", async () => {
    prismaAny.deliberation.findUnique.mockResolvedValue({ createdById: "someone-else" });
    prismaAny.deliberationRole.findMany.mockResolvedValue([{ role: "methodologist" }]);
    await expect(isModerator("delib-1", "u-x")).resolves.toBe(false);
  });

  it("is false for a null user or missing deliberation", async () => {
    await expect(isModerator("delib-1", null)).resolves.toBe(false);
    prismaAny.deliberation.findUnique.mockResolvedValue(null);
    await expect(isModerator("missing", "u")).resolves.toBe(false);
  });
});
