-- Add group chat support and message attachments
ALTER TABLE conversations
  ADD COLUMN title text,
  ADD COLUMN is_group boolean NOT NULL DEFAULT false,
  ALTER COLUMN user1_id DROP NOT NULL,
  ALTER COLUMN user2_id DROP NOT NULL;

CREATE TABLE conversation_participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT conversation_participants_conversation_id_user_id_key UNIQUE (conversation_id, user_id)
);

CREATE TABLE message_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  message_id bigint NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  url text NOT NULL,
  type text NOT NULL,
  size integer NOT NULL,
  metadata jsonb
);

ALTER TABLE messages
  ALTER COLUMN text DROP NOT NULL;

CREATE INDEX messages_conversation_id_created_at_idx ON messages (conversation_id, created_at);
