import '@/app/article.templates.css';   // <— single import
// import './article.global.scss';
import "@/app/article/editor.global.css";
import "@/app/article/rhetoric.css";

import "@/app/article/type-tokens.css";
import '@/app/fonts/fonts.css';



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ReaderLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex  justify-center items-center align-center  pb-4 h-full w-full  bg-white">
      {children}
      </body>
    </html>
  );
}

