import '@/app/article.templates.css';   // <— single import
// import './article.global.scss';
import "@/app/article/editor.global.css";
import "@/app/article/rhetoric.css";

import "@/app/article/type-tokens.css";
import '@/app/fonts/fonts.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex antialiased justify-center items-center align-center mt-0  py-0 h-full w-full  bg-slate-50 ">
        {children}
        </body>
    </html>
  )
}
