# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\" \n\x0c\x45mbedRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\t\",\n\tEmbedding\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"9\n\rEmbedResponse\x12(\n\nembeddings\x18\x01 \x03(\x0b\x32\x14.embedding.Embedding2K\n\x08\x45mbedder\x12?\n\nEmbedBatch\x12\x17.embedding.EmbedRequest\x1a\x18.embedding.EmbedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=30
  _globals['_EMBEDREQUEST']._serialized_end=62
  _globals['_EMBEDDING']._serialized_start=64
  _globals['_EMBEDDING']._serialized_end=108
  _globals['_EMBEDRESPONSE']._serialized_start=110
  _globals['_EMBEDRESPONSE']._serialized_end=167
  _globals['_EMBEDDER']._serialized_start=169
  _globals['_EMBEDDER']._serialized_end=244
# @@protoc_insertion_point(module_scope)
