// import "@/app/globals.css";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
// Layout shared by storefront + dashboard
import "@/app/globals.css";

import { ReactNode, Suspense } from 'react';
import { cookies } from 'next/headers';
import { prisma } from "@/lib/prismaclient";
export default async function StallLayout(
  { children, params }: { children: ReactNode; params: { id: string } },
) {
  // Example: fetch stall meta once per layout, pass via context/provider if needed
  const stallId = BigInt(params.id);            // Prisma model uses BigInt
  const stall   = await prisma.stall.findUnique({ where: { id: stallId } });
//   const stall = await prisma.stall.findUnique({ where: { id: params.stallId } });

  return (
    <>
      {/* Put a common stall header / branding here */}
      <header className="border-b p-2">
        <h1 className="text-[1.8rem] px-4 ml-2 font-semibold">{stall?.name}</h1>
      </header>

      {/* Suspense boundary allows streaming for child routes */}
      <Suspense fallback={<div className="p-4">Loading…</div>}>
        {children}
      </Suspense>
    </>
  );
}