CREATE TABLE IF NOT EXISTS "portfolio_pages" (
  "id" BIGSERIAL PRIMARY KEY,
  "slug" TEXT NOT NULL UNIQUE,
  "html" TEXT NOT NULL,
  "css" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
