CREATE TABLE IF NOT EXISTS user_taste_vectors (
  user_id BIGINT PRIMARY KEY REFERENCES auth.users(id),
  taste vector(256) NOT NULL,
  traits jsonb DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS scroll_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  dwell_ms INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS scroll_events_user_idx ON scroll_events (user_id);

CREATE INDEX IF NOT EXISTS user_taste_vectors_ann
  ON user_taste_vectors USING ivfflat (taste vector_cosine_ops) WITH (lists = 100);

CREATE MATERIALIZED VIEW IF NOT EXISTS user_dwell_avg AS
SELECT user_id, AVG(dwell_ms) AS avg_dwell_ms
FROM scroll_events
GROUP BY user_id;

DO $do$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM cron.job WHERE jobname = 'refresh_user_dwell_avg'
  ) THEN
    PERFORM cron.schedule(
      'refresh_user_dwell_avg',
      '*/5 * * * *',
      'REFRESH MATERIALIZED VIEW CONCURRENTLY user_dwell_avg'
    );
  END IF;
END
$do$;
