import '@/app/article.templates.css';   // <— single import
// import './article.global.scss';
import "@/app/article/editor.global.css";
import "@/app/article/rhetoric.css";

import "@/app/article/type-tokens.css";
import '@/app/fonts/fonts.css';
// import "@/app/globals.css";



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ReaderLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="justify-center items-center align-center mt-9  py-2 h-full w-full overflow-auto bg-[#eaeff0] ">
      {children}
      </body>
    </html>
  );
}