import '@/app/globals.css';
import '@/app/article.templates.css';   // <— single import
// import './article.global.scss';
import "@/app/article/editor.global.css";
import '@/app/fonts/fonts.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ReaderLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="justify-center items-center align-center mt-9  p-4 h-full w-full overflow-auto bg-slate-200 ">
      {children}
      </body>
    </html>
  );
}